# cluster.yaml
# A cluster with one managed node and fargte profile
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aquasec-fargatedemo
  region: us-west-1
  version: "1.28"

vpc:
  nat:
    gateway: Single # other options: Disable, Single (default)

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs:
      - "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
      roleOnly: true
      roleName: AmazonEKS_EBS_CSI_DriverRole

addons:
- name: aws-ebs-csi-driver
  version: latest
  serviceAccountRoleARN: arn:aws:iam::111222333444:role/AmazonEKS_EBS_CSI_DriverRole

managedNodeGroups:
  - name: managed-ng
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true

fargateProfiles:
  - name: yelb-secure
    selectors:
      # All workloads in the "yelb-secure" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: yelb-secure
